### ISSUE TITLE
New release for 2.18.1

### ISSUE THREAD

**Issue by Exelord** [ember-cli/ember-addon-output#5]
Ember-CLI 2.18.1 adds a very important change for testing on Travis in:
https://github.com/ember-cli/ember-cli/blob/v2.18.1/blueprints/app/files/testem.js

But as the blueprint is not available yet, there is no diff in upgrade comparison.
https://github.com/ember-cli/ember-addon-output/compare/v2.18.0...v2.18.1

The same situation is for app-output.

**Comment by Gaurav0** [comment]
Is there a process to do this or does someone do it manually and issue a PR?

**Comment by Turbo87** [comment]
@Gaurav0 https://github.com/ember-cli/ember-cli/blob/master/dev/add-to-output-repos.sh

but apparently when I released 2.18.1 something failed and caused this to not work correctly 🤔

**Comment by twokul** [comment]
@Exelord @Gaurav0 @Turbo87 I'm going to look into it this Friday.

**Comment by kellyselden** [comment]
Fixed. Sorry for the inconvenience.
