### ISSUE TITLE
Using import/export syntax in addon-test-support causing errors in eslint

### ISSUE THREAD

**Issue by kolybasov** [ember-cli/ember-addon-output#6]
I've tried to create test helpers for my addon but eslint throws errors because `addon-test-support` folder uses `sourceType: 'script`. Adding `'addon-test-support/**'` to my eslintrc fixes it. 

https://github.com/ember-cli/ember-addon-output/blob/82451684f5bd92f77ccc0c02095cf2af5de647a9/.eslintrc.js#L29-L33

I can submit PR for this just let me know.

**Comment by Turbo87** [comment]
@kolybasov thanks for reporting! this will need to be fixed in the https://github.com/ember-cli/ember-cli repo though. could you move the issue there?

**Comment by kolybasov** [comment]
@Turbo87 did it https://github.com/ember-cli/ember-cli/issues/7652 Closing this issue.
